/**
 *  Copyright 2017 Dex`s Studio
 *  All right reserved.
 *  Created on Apr 10, 2017 11:08:45 PM
 *  @author Dex
 *  @email  Edgar_wdx@hotmail.com
 */
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.
*/

import generator.StringRandom;

public class Solution389 {
	public static void main(String[] args) {
		String input1 = StringRandom.strAlphabetGen(10);
		String input2 = input1 + "c";
		
		System.out.print(findTheDifference(input1,input2));
	}
	
    public static char findTheDifference(String s, String t) 
    {
    	int counter = t.charAt(s.length());
    	for(int i =0 ; i < s.length(); i++)
    	{
    		counter -= s.charAt(i);
    		counter += t.charAt(i);
    	}
    	return (char) counter;
    }

}
